# An example that demonstrates how to apply analysis to a JSONL file with sensor logs in real-time via REST events.
# usage:
#   python -m examples.lens_sensor_logs_rest --api_key=<YOUR_API_KEY> --filename=<JSONL_FILE_ID>
import logging
import json

from archetypeai import ArchetypeAI, ArgParser

def stream_jsonl_file(filename: str) -> dict:
    """Loads a JSONL file and yields one JSON object at a time."""
    with open(filename, "r") as file_handle:
        for line in file_handle:
            if line.strip():  # Skip empty lines.
                yield json.loads(line)

def main(args):
    # Create a new client using your unique API key.
    client = ArchetypeAI(args.api_key, api_endpoint=args.api_endpoint)

    # Note we don't have to upload any file as we stream it directly in the session callback.

    # Create a custom lens and automatically launch the lens session.
    client.lens.create_and_run_lens(f"""
       lens_name: Sensor Log Detector
       lens_config:
        model_pipeline:
          - processor_name: lens_sensor_logs_processor
        model_parameters:
            model_version: Newton::c2_4_7b_251215a172f6d7
            instruction: {args.instruction}
            focus: {args.focus}
            sensor_buffer_size: {args.sensor_buffer_size}
            input_buffer_step_size: {args.input_buffer_step_size}
        # Note no input stream is defined as we directly inject events in the session.
        output_streams:
            - stream_type: server_sent_events_writer
    """, session_callback, client=client, args=args)

def session_callback(
        session_id: str,
        session_endpoint: str,
        client: ArchetypeAI,
        args: dict
    ) -> None:
    """Main function to run the logic of a custom lens session."""
    # Validate the session is ready.
    event_message = {"type": "session.validate"}
    response = client.lens.sessions.process_event(session_id, event_message)
    assert response["event_data"]["is_valid"], response

    # Stream the JSON values from the JSONL file and send them to the active session.
    # In this example, we read and upload the JSON file line by line to the lens, then
    # we open the SSE and read back the results. In a real-time application, the events
    # could be generated by a live sensor stream and sent to the lens in parallel with
    # reading the real-time output from the SSE stream.
    for json_row in stream_jsonl_file(args.filename):
        event = {
            "type": "session.update",
            "event_data": {
                "type": "data.json",
                "event_data": json_row,
            }
        }
        response = client.lens.sessions.process_event(session_id, event)
        logging.info(response)

    # Create a SSE reader to read the output of the lens.
    sse_reader = client.lens.sessions.create_sse_consumer(
        session_id, max_read_time_sec=args.max_run_time_sec)

    # Read events from the SSE stream until either the last message is
    # received or the max read time has been reached.
    for event in sse_reader.read(block=True):
        logging.info(f"[sse_reader] {event}")

    # Close any active reader.
    sse_reader.close()


if __name__ == "__main__":
    parser = ArgParser()
    parser.add_argument("--filename", required=True, type=str)
    parser.add_argument("--instruction", default="Analyze the sensor data in the text logs with the following focus.", type=str)
    parser.add_argument("--focus", default="Output an alert if a user enters the kitchen. Consider a door open/closed event or faucet on/off event as a person present.", type=str)
    parser.add_argument("--sensor_buffer_size", default=5, type=int, help="The number of JSONL rows buffered by the lens that are sent to Newton.")
    parser.add_argument("--input_buffer_step_size", default=1, type=int, help="The step size for sampling incoming sensor events. A value of 1 means every row is read and input to the lens.")
    parser.add_argument("--max_run_time_sec", default=-1.0, type=float)
    args = parser.parse_args(configure_logging=True)

    # Validate the input.
    assert args.filename.endswith(".jsonl"), "Enter a valid .jsonl file"

    main(args)