# An example that demonstrates how to apply analysis to JSON sensor logs in real-time via REST events.
# usage:
#   python -m examples.lens_sensor_logs_rest --api_key=<YOUR_API_KEY>
import logging

from archetypeai import ArchetypeAI, ArgParser


def main(args):
    # Create a new client using your unique API key.
    client = ArchetypeAI(args.api_key, api_endpoint=args.api_endpoint)

    # Note we don't have to upload any file as we stream it directly in the session callback.

    # Create a custom lens and automatically launch the lens session.
    client.lens.create_and_run_lens(f"""
       lens_name: Sensor Log Detector
       lens_config:
        model_pipeline:
          - processor_name: lens_sensor_logs_processor
        model_parameters:
            model_version: Newton::c2_4_7b_251215a172f6d7
            instruction: {args.instruction}
            focus: {args.focus}
            sensor_buffer_size: {args.sensor_buffer_size}
        # Note no input stream is defined as we directly inject events in the session.
        output_streams:
            - stream_type: server_sent_events_writer
    """, session_callback, client=client, args=args)

def session_callback(
        session_id: str,
        session_endpoint: str,
        client: ArchetypeAI,
        args: dict
    ) -> None:
    """Main function to run the logic of a custom lens session."""
    # Validate the session is ready.
    event_message = {"type": "session.validate"}
    response = client.lens.sessions.process_event(session_id, event_message)
    assert response["event_data"]["is_valid"], response

    # Stream some fake JSON sensor data to the active session. In this example, we generate
    # the JSON data and stream it to the lens, then we open the SSE and read back the results.
    # In a real-time application, the events could be generated by a live sensor stream and
    # sent to the lens in parallel with reading the real-time output from the SSE stream.
    for counter_value in range(10):
        # Generate a fake sensor event.
        sensor_event = {"sensor_id": "sensor_1", "value": counter_value}
        event = {
            "type": "session.update",
            "event_data": {
                "type": "data.json",
                "event_data": sensor_event,
            }
        }
        response = client.lens.sessions.process_event(session_id, event)
        logging.info(response)

    # Create a SSE reader to read the output of the lens.
    sse_reader = client.lens.sessions.create_sse_consumer(
        session_id, max_read_time_sec=args.max_run_time_sec)

    # Read events from the SSE stream until either the last message is
    # received or the max read time has been reached.
    for event in sse_reader.read(block=True):
        logging.info(f"[sse_reader] {event}")

    # Close any active reader.
    sse_reader.close()


if __name__ == "__main__":
    parser = ArgParser()
    parser.add_argument("--instruction", default="Analyze the sensor data in the text logs with the following focus.", type=str)
    parser.add_argument("--focus", default="Output an alert if the sensor value excceeds 5.", type=str)
    parser.add_argument("--sensor_buffer_size", default=1, type=int, help="The number of JSON rows buffered by the lens that are sent to Newton.")
    parser.add_argument("--max_run_time_sec", default=-1.0, type=float)
    args = parser.parse_args(configure_logging=True)

    main(args)